### ISSUE TITLE
Urgente: Las tablas se eliminan de la base de datos

### ISSUE THREAD

**Issue by pipeCer** [MISW-Basinglo/abcall-backend#30]
En momentos aleatorios, las tablas en la base de datos dejan de existir por alguna razón. Al revisar los logs, se encuentra un comando de "fast shutdown".

Debemos investigar y arreglarlo.
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/ef4a70e5-7a95-4de3-88a5-282b487d3de6">

**Comment by Richardace** [comment]
Se configura la BD en Cloud SQL de GCP.
![image](https://github.com/user-attachments/assets/948db476-9fde-4ec7-af7f-cc473c4dbf00)
